# Generated by Django 3.1.7 on 2021-03-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='room_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
