# Generated by Django 3.1.7 on 2021-04-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='current_session',
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='session_started_on',
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='session_will_end_on',
        ),
        migrations.AddField(
            model_name='discorduser',
            name='session_end',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
