# Generated by Django 3.1.7 on 2021-04-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_discorduser_gonna_plant_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='gonna_plant_tree_on',
            field=models.IntegerField(default=0),
        ),
    ]
