# Generated by Django 3.1.7 on 2021-04-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210401_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='session_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
