# Generated by Django 3.1.7 on 2021-04-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_discorduser_slowmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
