# Generated by Django 3.1.7 on 2021-04-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_discorduser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
