# Generated by Django 3.1.7 on 2021-04-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_store_item_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.IntegerField(default=1),
        ),
    ]
